${XL_IDP_ROOT}/bash_dir/line_admiral.sh
${XL_IDP_ROOT}/bash_dir/line_akkon_lines.sh
${XL_IDP_ROOT}/bash_dir/line_arkas.sh
${XL_IDP_ROOT}/bash_dir/line_cma_cgm.sh
${XL_IDP_ROOT}/bash_dir/line_cosco.sh
${XL_IDP_ROOT}/bash_dir/line_economou.sh
${XL_IDP_ROOT}/bash_dir/line_evergreen.sh
${XL_IDP_ROOT}/bash_dir/line_fesco.sh
${XL_IDP_ROOT}/bash_dir/line_lider_line.sh
${XL_IDP_ROOT}/bash_dir/line_maersk.sh
${XL_IDP_ROOT}/bash_dir/line_milaha.sh
${XL_IDP_ROOT}/bash_dir/line_msc.sh
${XL_IDP_ROOT}/bash_dir/line_one.sh
${XL_IDP_ROOT}/bash_dir/line_oocl.sh
${XL_IDP_ROOT}/bash_dir/line_yang_ming.sh
${XL_IDP_ROOT}/bash_dir/line_zim.sh
